server:
  port: 8889
  context-path: /whxj
spring:
    datasource:
        url: jdbc:mysql://192.168.232.136:6606/mysitedb
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver